import tempfile
import threading
import numpy as np
import tensorflow as tf
import logging

from Metadata_Processor import MetadataAPIProcessor
from Signal_Processor import SignalAPIProcessor
from settings import (
    MODEL_PATH, BEST_THRESHOLDS, DEMO_MODE,
    OPENAI_API_KEY, FINE_TUNED_MODEL, REPORT_TEMPERATURE,
    BINARY_MODEL_DIR,
)
from ecg_engine import (
    load_ecg_model, load_binary_model, run_binary_inference,
    get_signal_from_files,
    estimate_heart_rate, estimate_rhythm_regularity,
    slice_signal_windows,
)
from gpt_report import generate_ecg_report
from xai_engine import compute_integrated_gradients

log = logging.getLogger(__name__)

# ── Thread-safe model singleton ────────────────────────────────────────────────
_MODEL = None
_MODEL_LOCK = threading.Lock()

# ── Binary pre-filter model singleton ──────────────────────────────────────────
_BINARY_MODEL = None
_BINARY_MODEL_LOCK = threading.Lock()

def _get_binary_model():
    global _BINARY_MODEL
    with _BINARY_MODEL_LOCK:
        if _BINARY_MODEL is None:
            _BINARY_MODEL = load_binary_model(BINARY_MODEL_DIR)
    return _BINARY_MODEL

def get_binary_model():
    return _get_binary_model()

SIG_PROC = SignalAPIProcessor()
META_PROC = MetadataAPIProcessor()

def _get_model():
    global _MODEL
    with _MODEL_LOCK:
        if _MODEL is None:
            _MODEL = load_ecg_model(MODEL_PATH)
    return _MODEL

def get_model():
    return _get_model()


LABELS_LIST = ['NORM', 'MI', 'STTC', 'CD', 'HYP']

def run_inference(model, metadata_arr, signal_arr):
    """
    Run model inference and return predictions, best_idx, probabilities.
    If model is None, returns realistic mock data.
    """
    thresholds_dict = dict(zip(LABELS_LIST, BEST_THRESHOLDS))

    if model is None:
        probabilities = np.array([0.12, 0.84, 0.09, 0.41, 0.07])
    else:
        logits = model.predict([metadata_arr, signal_arr], verbose=0)
        probabilities = tf.nn.sigmoid(logits).numpy()[0]

    detected_indices_raw = [i for i, p in enumerate(probabilities) if p >= thresholds_dict[LABELS_LIST[i]]]
    raw_detected_labels = [LABELS_LIST[i] for i in detected_indices_raw]
    has_pathology = any(lbl != 'NORM' for lbl in raw_detected_labels)

    final_detected_indices = []
    if has_pathology and 'NORM' in raw_detected_labels:
        final_detected_indices = [i for i in detected_indices_raw if LABELS_LIST[i] != 'NORM']
    else:
        final_detected_indices = detected_indices_raw

    predictions = []
    for i, label in enumerate(LABELS_LIST):
        prob = float(probabilities[i])
        is_positive = i in final_detected_indices
        predictions.append((label, prob, is_positive))

    if not final_detected_indices:
        best_idx = int(np.argmax(probabilities))
    else:
        det_probs = [probabilities[i] for i in final_detected_indices]
        best_idx = final_detected_indices[np.argmax(det_probs)]

    return predictions, best_idx, probabilities


def _generate_fallback_report(predictions, age, sex, hr, heart_rhythm, rhythm_reg):
    """Generate a basic markdown report when LLM is unavailable."""
    active = [name for name, prob, is_pos in predictions if is_pos]
    if not active:
        active = [max(predictions, key=lambda x: x[1])[0]]

    report = f"""## Clinical Interpretation Report

**Patient:** {age}-year-old {sex}
**Vitals:** Heart Rate {hr} bpm | Rhythm: {heart_rhythm} | Regularity: {rhythm_reg}

### Diagnostic Summary
The ECG analysis indicates the following condition(s): **{', '.join(active)}**.

### Clinical Correlation
Based on the automated pattern recognition, the model has identified features consistent with {active[0]}. 
Further clinical evaluation and correlation with patient symptoms and history are recommended.

### Recommendations
- Consult cardiology if this is an acute presentation.
- Compare with prior ECGs if available.
- Consider additional cardiac biomarkers (troponin, BNP) as clinically indicated.

*This report was generated by CardioInsight AI (Demo Mode).*
"""
    return report


# ── Full pipeline (single record) ─────────────────────────────────────────────

def run_full_pipeline(
    hea_bytes: bytes, hea_name: str,
    dat_bytes: bytes, dat_name: str,
    age: int,
    sex: str,
    height: float | None = None,
    weight: float | None = None,
) -> dict:

    with tempfile.TemporaryDirectory() as tmp_dir:
        signal_raw_data, fs = get_signal_from_files(hea_bytes, hea_name, dat_bytes, dat_name, tmp_dir)
        signal_arr = SIG_PROC.process_for_api(signal_raw_data)

    sex_num = 0 if str(sex).lower() in ["male", "0", "0.0"] else 1
    metadata_arr = META_PROC.process_metadata_for_api(age, sex_num, height, weight)

    model = _get_model()
    predictions, best_idx, probabilities = run_inference(model, metadata_arr, signal_arr)

    hr = estimate_heart_rate(signal_raw_data, fs)
    heart_rhythm, rhythm_reg = estimate_rhythm_regularity(signal_raw_data, fs)

    # Report generation with fallback
    try:
        report = generate_ecg_report(
            predictions=predictions,
            api_key=OPENAI_API_KEY,
            model_id=FINE_TUNED_MODEL,
            temperature=REPORT_TEMPERATURE,
            meta={"age": age, "sex": sex, "hr": hr, "heart_rhythm": heart_rhythm, "rhythm_regularity": rhythm_reg},
        )
    except Exception as exc:
        log.warning("LLM report generation failed: %s. Using fallback.", exc)
        report = _generate_fallback_report(predictions, age, sex, hr, heart_rhythm, rhythm_reg)

    # XAI - Integrated Gradients for importance
    ig_signal = np.zeros_like(signal_arr[0])
    ig_meta = np.zeros(metadata_arr.shape[1])

    try:
        if model is not None:
            ig_meta, ig_signal = compute_integrated_gradients(
                model, metadata_arr, signal_arr, class_index=best_idx, n_steps=50
            )
            lead_importance = np.mean(np.abs(ig_signal), axis=0).tolist()
            meta_importance = ig_meta.tolist()
        else:
            raise RuntimeError("Model not available: skipping IG computation.")
    except Exception as e:
        log.warning("Error computing IG for importance: %s", e)
        lead_importance = [0.0] * signal_arr.shape[-1]
        meta_importance = [0.0] * len(metadata_arr[0])

    return {
        "predictions": predictions,
        "report": report,
        "signal": signal_raw_data,
        "signal_arr": signal_arr,
        "metadata_arr": metadata_arr,
        "fs": fs,
        "ig_signal": ig_signal,
        "meta": {
            "age": age,
            "sex": sex,
            "height": height,
            "weight": weight,
            "hr": hr,
            "heart_rhythm": heart_rhythm,
            "rhythm_regularity": rhythm_reg,
            "best_idx": int(best_idx),
            "lead_importance": lead_importance,
            "meta_importance": meta_importance,
        },
    }


# ── Batch pipeline ────────────────────────────────────────────────────────────

def run_batch_pipeline(records: list[dict]) -> list[dict]:
    """
    Process multiple ECG records.
    records: list of dicts with keys: hea_bytes, hea_name, dat_bytes, dat_name, age, sex, height, weight
    Returns: list of result dicts
    """
    results = []
    for rec in records:
        try:
            result = run_full_pipeline(**rec)
            result["status"] = "success"
            result["filename"] = rec["hea_name"]
        except Exception as exc:
            result = {
                "status": "error",
                "filename": rec["hea_name"],
                "error": str(exc),
                "predictions": [("NORM", 0.12, False), ("MI", 0.84, True), ("STTC", 0.09, False), ("CD", 0.41, False), ("HYP", 0.07, False)],
                "report": f"Error processing {rec['hea_name']}: {exc}",
            }
        results.append(result)
    return results


# ── Streaming pipeline ────────────────────────────────────────────────────────

def run_streaming_pipeline(
    continuous_signal: np.ndarray,
    fs: float,
    age: int,
    sex: str,
    height: float | None = None,
    weight: float | None = None,
    window_sec: float = 10.0,
    overlap_sec: float = 5.0,
):
    """
    Real-time streaming pipeline:
      1. Slice continuous signal into overlapping windows.
      2. Run lightweight binary pre-filter (signal only).
      3. If abnormal (1), run full multi-label model with metadata for detailed diagnosis.

    Yields a dict per window for real-time display.
    """
    sex_num = 0 if str(sex).lower() in ["male", "0", "0.0"] else 1
    metadata_arr = META_PROC.process_metadata_for_api(age, sex_num, height, weight)

    multi_model = _get_model()
    binary_model = _get_binary_model()

    windows = slice_signal_windows(continuous_signal, fs, window_sec, overlap_sec)

    for win_idx, (window_signal, start, end) in enumerate(windows):
        signal_arr = SIG_PROC.process_for_api(window_signal)

        # Step 1: Binary pre-filter (fast, no metadata required)
        if binary_model is not None:
            binary_pred, binary_conf = run_binary_inference(binary_model, signal_arr)
        else:
            # If binary model is missing, force detailed analysis so the demo still works
            binary_pred = 1
            binary_conf = 1.0

        # Step 2: Detailed multi-label analysis only if binary flags abnormal
        if binary_pred == 1:
            predictions, best_idx, probabilities = run_inference(multi_model, metadata_arr, signal_arr)
        else:
            # Normal window — skip heavy model, return clean NORM
            predictions = [
                ("NORM", float(binary_conf), True),
                ("MI", 0.05, False),
                ("STTC", 0.04, False),
                ("CD", 0.03, False),
                ("HYP", 0.02, False),
            ]
            best_idx = 0

        hr = estimate_heart_rate(window_signal, fs)
        heart_rhythm, rhythm_reg = estimate_rhythm_regularity(window_signal, fs)

        yield {
            "window_idx": win_idx,
            "start_sample": start,
            "end_sample": end,
            "start_sec": start / fs,
            "end_sec": end / fs,
            "fs": fs,
            "window_signal": window_signal,
            "binary_pred": binary_pred,
            "binary_conf": binary_conf,
            "predictions": predictions,
            "best_idx": best_idx,
            "hr": hr,
            "heart_rhythm": heart_rhythm,
            "rhythm_regularity": rhythm_reg,
            "anomaly_flag": binary_pred == 1,
        }


# ── Full-result analysis for a flagged streaming window ───────────────────────

def run_streaming_window_analysis(
    window_signal: np.ndarray,
    fs: float,
    age: int,
    sex: str,
    height: float | None = None,
    weight: float | None = None,
) -> dict:
    """
    Run the same full-result pipeline used for Manual Upload (multi-label
    inference + LLM report + Integrated-Gradients importance) on a single
    ~10s window flagged abnormal by the streaming binary pre-filter.

    Returns a dict with the exact same shape as run_full_pipeline's return
    value, so the caller can reuse the Manual Upload results renderer as-is.
    """
    signal_arr = SIG_PROC.process_for_api(window_signal)

    sex_num = 0 if str(sex).lower() in ["male", "0", "0.0"] else 1
    metadata_arr = META_PROC.process_metadata_for_api(age, sex_num, height, weight)

    model = _get_model()
    predictions, best_idx, probabilities = run_inference(model, metadata_arr, signal_arr)

    hr = estimate_heart_rate(window_signal, fs)
    heart_rhythm, rhythm_reg = estimate_rhythm_regularity(window_signal, fs)

    try:
        report = generate_ecg_report(
            predictions=predictions,
            api_key=OPENAI_API_KEY,
            model_id=FINE_TUNED_MODEL,
            temperature=REPORT_TEMPERATURE,
            meta={"age": age, "sex": sex, "hr": hr, "heart_rhythm": heart_rhythm, "rhythm_regularity": rhythm_reg},
        )
    except Exception as exc:
        log.warning("LLM report generation failed: %s. Using fallback.", exc)
        report = _generate_fallback_report(predictions, age, sex, hr, heart_rhythm, rhythm_reg)

    ig_signal = np.zeros_like(signal_arr[0])
    ig_meta = np.zeros(metadata_arr.shape[1])

    try:
        if model is not None:
            ig_meta, ig_signal = compute_integrated_gradients(
                model, metadata_arr, signal_arr, class_index=best_idx, n_steps=50
            )
            lead_importance = np.mean(np.abs(ig_signal), axis=0).tolist()
            meta_importance = ig_meta.tolist()
        else:
            raise RuntimeError("Model not available: skipping IG computation.")
    except Exception as e:
        log.warning("Error computing IG for importance: %s", e)
        lead_importance = [0.0] * signal_arr.shape[-1]
        meta_importance = [0.0] * len(metadata_arr[0])

    return {
        "predictions": predictions,
        "report": report,
        "signal": window_signal,
        "signal_arr": signal_arr,
        "metadata_arr": metadata_arr,
        "fs": fs,
        "ig_signal": ig_signal,
        "meta": {
            "age": age,
            "sex": sex,
            "height": height,
            "weight": weight,
            "hr": hr,
            "heart_rhythm": heart_rhythm,
            "rhythm_regularity": rhythm_reg,
            "best_idx": int(best_idx),
            "lead_importance": lead_importance,
            "meta_importance": meta_importance,
        },
    }
